CREATE TABLE t25(
				id INT,
				`name` VARCHAR(32))
				
SHOW INDEXES FROM t25

CREATE UNIQUE INDEX id_index on t25(id)

CREATE INDEX id_index ON t25(id)

CREATE TABLE t26(
				id INT,
				`name` VARCHAR(32))
ALTER TABLE t26 ADD PRIMARY KEY (id)

SHOW INDEX FROM t26

DROP INDEX id_index ON t25

ALTER TABLE t26 DROP PRIMARY KEY

SHOW INDEX FROM t24
SHOW INDEXES FROM t24
SHOW KEYS FROM t24
				